import BaseFileClient from "@components/BaseFileClient";
import Header from "@components/header/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        <BaseFileClient />
        <Header />
        {children}
      </body>
    </html>
  );
}
