import BaseFileClient from "@components/BaseFileClient";
import Footer from "@components/footer/Footer";
import Header from "@components/header/Header";
import { AuthProvider } from "@context/AuthContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        <BaseFileClient />
        <AuthProvider>
          <Header />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
